name: Sync Workflows to Other Repos

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'  # Trigger only when workflow files change

jobs:
  sync-workflows:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with the workflows
      - name: Checkout central workflows repository
        uses: actions/checkout@v2

      # Set up Git user identity
      - name: Set up Git user identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Sync workflows to target repositories
      - name: Sync workflows to other repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}  # Ensure this secret is correctly named
        run: |
          # List of target repositories to sync workflows to
          REPOS=("machine-learning-opdracht-jari-heeres")  # Add more repo names if needed
          
          # Loop through each repository and sync workflows
          for REPO in "${REPOS[@]}"; do
            echo "Syncing workflows to $REPO"

            # Clone the target repository using authentication
            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/jheeres-visionplanner/$REPO.git
            cd $REPO

            # Copy the workflows from the central repo
            cp -r ../.github/workflows/* .github/workflows/

            # Commit and push the changes
            git add .github/workflows/
            git commit -m "Sync workflows from central repository"
            git push origin main

            # Go back to the root directory for the next repo
            cd ..
          done
